name: Release

on:
  release:
    types: [created]

jobs:
  release-binaries:
    name: Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [arm, arm64, amd64]
        exclude:
        - goarch: arm
          goos: darwin
        - goarch: arm
          goos: windows
        - goarch: arm64
          goos: windows
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.30
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        project_path: "./cmd/ariel"
        binary_name: "ariel"
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.21.3
        extra_files: LICENSE