name: Release

on:
  release:
    types: [created]

jobs:
  release-binaries:
    name: Release Binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [darwin]
        goarch: [arm,arm64]
        exclude:
        - goarch: arm
          goos: darwin
    steps:
    - uses: actions/checkout@v3
    - run: ls -al
    - uses: wangyoucao577/go-release-action@v1.40
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        project_path: "./cmd/ariel"
        binary_name: "ariel"
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.21.3
        extra_files: LICENSE